// Generated by meowlive-protocol/export-types. Do not edit.

export const PROTOCOL_VERSION = 3 as const;

export type ChatReadMode = "auto" | "all" | "selective";

export type InteractionSettings = { chat_read_mode: ChatReadMode, welcome_enabled: boolean, busy_chat_count: number, busy_enter_count: number, busy_pending_count: number, welcome_cooldown_ms: number, welcome_viewer_cooldown_ms: number, };

export type MergeViewerSummary = { viewer_id: string, alias: string | null, identities: number, events: number, memories: number, relationships: number, familiarity_milli: number, affinity_milli: number, };

export type ViewerMergePreview = { source: MergeViewerSummary, target: MergeViewerSummary, revision: number, fingerprint: string, resulting_familiarity_milli: number, resulting_affinity_milli: number, risks: Array<string>, };

export type ViewerMergePreviewRequest = { source_viewer_id: string, target_viewer_id: string, };

export type ViewerMergeRequest = { source_viewer_id: string, target_viewer_id: string, expected_revision: number, fingerprint: string, request_key: string, reason: string, confirmed: boolean, };

export type ViewerMergeOutcome = { canonical_viewer_id: string, revision: number, };

export type RelationshipEntity = { kind: string, id: string, };

export type RelationshipEvidence = { source: string, event_id: string, quote: string, };

export type ViewerRelationship = { id: string, version: number, source: RelationshipEntity, target: RelationshipEntity, kind: string, confirmation: string, evidence: Array<RelationshipEvidence>, expires_at_ms: number | null, deleted: boolean, };

export type RelationshipPage = { relationships: Array<ViewerRelationship>, degraded: boolean, };

export type RelationshipCreateRequest = { source: RelationshipEntity, target: RelationshipEntity, kind: string, evidence: Array<RelationshipEvidence>, expires_at_ms: number | null, admin_confirmed: boolean, reason: string, request_key: string, };

export type RelationshipChangeRequest = { expected_version: number, action: string, reason: string, request_key: string, };

export type KnowledgeMaintenanceRequest = { request_key: string, reason: string, };

export type GraphStatus = { pending: number, leased: number, failed: number, oldest_pending_age_ms: number | null, connected: boolean, };

export type AffinityLedgerEntry = { ledger_id: string, kind: string, computed_delta_milli: number, applied_delta_milli: number, reason: string, actor: string, created_at_ms: number, reversed_ledger_id: string | null, reversible: boolean, };

export type GiftLedgerEntry = { source: string, event_id: string, name: string, count: number, metadata: GiftMetadataInput | null, value_cents: number | null, value_kind: string, occurred_at_ms: number, };

export type CompanionshipDetail = { viewer_id: string, familiarity_milli: number, affinity_milli: number, observed_days: number, observed_sessions: number, last_seen_at_ms: number, medal_level: number | null, guard_level: number | null, gifts: Array<GiftLedgerEntry>, ledger: Array<AffinityLedgerEntry>, };

export type AffinityAdjustmentRequest = { request_key: string, reason: string, delta_milli: number, };

export type AffinityReversalRequest = { request_key: string, reason: string, ledger_id: string, };

export type GiftConfirmationRequest = { request_key: string, reason: string, source: string, event_id: string, value_cents: number, value_kind: string, };

export type AdminMutationResult = { record_id: string, };

export type CompanionshipHealth = { durable_receipts: boolean, failed_receipts: Array<ReceiptProblem>, pending_receipts: number, failed_receipt_attempts: number, };

export type ReceiptProblem = { speech_id: string, attempts: number, };

export type MemoryEvidence = { source: string, event_id: string, quote: string, occurred_at_ms: number, };

export type ViewerMemory = { id: string, viewer_id: string, key: string, value: string, kind: string, status: string, version: number, locked: boolean, deleted: boolean, expires_at_ms: number | null, evidence: Array<MemoryEvidence>, };

export type MemoryPage = { memories: Array<ViewerMemory>, };

export type MemoryMutationRequest = { request_key: string, reason: string, expected_version: number, operation: string, value: string | null, frozen: boolean | null, };

export type MemoryJobsStatus = { pending: number, running: number, failed: number, embedding_pending: number, embedding_failed: number, };

export type AdminSessionRequest = { token: string, };

export type AdminSessionStatus = { enabled: boolean, authenticated: boolean, };

export type AdminSessionToken = { token: string, expires_in_seconds: number, };

export type ViewerAlias = { alias: string, first_seen_at_ms: number, last_seen_at_ms: number, };

export type ViewerIdentity = { platform: string, namespace: string, id_kind: string, external_id: string, last_confirmed_at_ms: number, };

export type ViewerSummary = { viewer_id: string, current_alias: string | null, alias_observed_at_ms: number | null, identities: Array<ViewerIdentity>, aliases: Array<ViewerAlias>, };

export type PersistedViewerEvent = { event_id: string, source: string, session_id: string, viewer_id: string | null, viewer: string, occurred_at_ms: number, received_at_ms: number, kind: EventPayload, gift_metadata: GiftMetadataInput | null, };

export type ViewerPage = { scope_id: string, viewers: Array<ViewerSummary>, offset: number, };

export type ViewerEventPage = { scope_id: string, events: Array<PersistedViewerEvent>, offset: number,
/**
 * Since this server process started; absence of a counter is not proof of complete upstream data.
 */
unconfirmed_events: number, };

export type LlmPrice = { provider: string, base_url: string, model: string, input_usd_per_million: number, output_usd_per_million: number, cache_read_usd_per_million: number, cache_write_usd_per_million: number, };

export type AgentRuntimeSettings = { cache_enabled: boolean, streaming: boolean, tools_enabled: boolean, environment_enabled: boolean, web_search_enabled: boolean,
/**
 * brave / searxng
 */
search_provider: string, search_endpoint: string, max_tool_rounds: number, tool_timeout_seconds: number, prices: Array<LlmPrice>, };

export type AgentRuntimeSettingsSnapshot = { settings: AgentRuntimeSettings, search_key_configured: boolean, storage_available: boolean, };

export type AgentRuntimeSettingsRequest = { settings: AgentRuntimeSettings, search_api_key: string | null, clear_search_api_key: boolean, };

export type LlmTokenUsage = { input_tokens: number | null, output_tokens: number | null, cache_read_tokens: number | null, cache_write_tokens: number | null, reasoning_tokens: number | null, };

export type LlmUsageRecord = { id: string, trace_id?: string, turn_id?: string, tool_round?: number, retry_attempt?: number, started_at_ms: number, provider: string, api_format: string, base_url: string, model: string, operation: string,
/**
 * running / completed / failed / cancelled / interrupted
 */
status: string, latency_ms: number, first_token_ms: number | null, usage: LlmTokenUsage,
/**
 * 微美元，null 表示未报告用量或未配置单价。
 */
estimated_cost_microusd: number | null, };

export type LlmUsageTotals = { calls: number, input_tokens: number, output_tokens: number, cache_read_tokens: number, cache_write_tokens: number, reasoning_tokens: number, estimated_cost_microusd: number, unpriced_calls: number, unknown_usage_calls: number, };

export type LlmUsageGroup = { provider: string, base_url: string, model: string, totals: LlmUsageTotals, };

export type LlmUsageSnapshot = { totals: LlmUsageTotals, groups: Array<LlmUsageGroup>, records: Array<LlmUsageRecord>, storage_available: boolean, truncated: boolean, };

export type AgentToolActivity = { name: string,
/**
 * running / completed / failed
 */
status: string, elapsed_ms: number, sources: Array<string>, };

export type AgentActivitySnapshot = { run_id: string | null,
/**
 * idle / thinking / receiving / tool / completed / failed / cancelled
 */
phase: string, started_at_ms: number | null, updated_at_ms: number, output_characters: number, tool_round: number, tools: Array<AgentToolActivity>, message: string, };

export type AgentSchedulerBlockReason = "ready" | "paused" | "model_unavailable" | "bridge_disconnected" | "resource_changing" | "gpu_busy" | "synthesizer_busy" | "receipt_backlog" | "playback_busy" | "decision_in_flight" | "speech_in_flight" | "cooldown" | "completion_buffer_full" | "work_id_exhausted" | "no_eligible_events";

export type AgentSchedulerSnapshot = { ready: boolean, phase: AgentPhase, block_reason: AgentSchedulerBlockReason, message: string, remaining_ms: number | null, pending_events: number, deciding_events: number, active_speeches: number, updated_at_ms: number, };

export type AgentTraceStatus = "running" | "completed" | "failed" | "cancelled" | "interrupted";

export type AgentTraceStepKind = "scheduled" | "context_ready" | "turn_started" | "first_token" | "turn_finished" | "tool_started" | "tool_finished" | "decision_received" | "validation_finished" | "speech_queued" | "speech_synthesizing" | "speech_ready" | "speech_playing" | "trace_finished";

export type AgentTraceStepStatus = "running" | "completed" | "failed" | "cancelled";

export type AgentTraceStep = { sequence: number, occurred_at_ms: number, kind: AgentTraceStepKind, status: AgentTraceStepStatus, message: string, turn_id: string | null, tool_name: string | null, speech_id: string | null, elapsed_ms: number | null, sources: Array<string>, };

export type AgentTraceEvent = { id: string, kind: string, viewer: string, summary: string, };

export type AgentTurn = { id: string, index: number, tool_round: number, retry_attempt: number, provider: string, api_format: string, model: string, status: AgentTraceStatus, started_at_ms: number, first_token_ms: number | null, finished_at_ms: number | null, latency_ms: number, usage: LlmTokenUsage, };

export type AgentTraceSummary = { id: string, status: AgentTraceStatus, trigger: string, started_at_ms: number, updated_at_ms: number, finished_at_ms: number | null, event_count: number, turn_count: number, tool_count: number, speech_id: string | null, result: string, truncated: boolean, };

export type AgentTrace = { summary: AgentTraceSummary, events: Array<AgentTraceEvent>, turns: Array<AgentTurn>, steps: Array<AgentTraceStep>, };

export type AgentTraceList = { traces: Array<AgentTraceSummary>, storage_available: boolean, truncated: boolean, };

export type LlmSettings = { provider: string, api_format: string, base_url: string, model: string, mode: string, timeout_seconds: number, max_tokens: number, json_mode: boolean, reasoning_effort: string, };

export type LlmSettingsSnapshot = { settings: LlmSettings, key_configured: boolean, restart_required: boolean, active_model: string, storage_available: boolean, profiles: Array<LlmProfileSummary>, selected_profile_id: string | null, };

export type LlmProfileSummary = { id: string, name: string, settings: LlmSettings, key_configured: boolean, };

export type LlmSettingsRequest = { settings: LlmSettings, api_key: string | null, clear_api_key: boolean, };

export type LlmProfileCreateRequest = { name: string, settings: LlmSettings, api_key: string | null, clear_api_key: boolean, };

export type LlmProfileIdRequest = { id: string, };

export type LlmProfileRenameRequest = { id: string, name: string, };

export type LlmReasoningRequest = { provider: string, api_format: string, model: string, reasoning_effort: string, max_tokens: number, };

export type LlmReasoningResult = { requested: string, effective: string | null, supported: Array<string>, strategy: string, budget_tokens: number | null, note: string, error: string | null, };

export type LlmTestResult = { message: string, };

export type LlmModelsRequest = { provider: string, api_format: string, base_url: string, mode: string, api_key: string | null, clear_api_key: boolean, };

export type LlmModelOption = { id: string, name: string, };

export type LlmModelsResult = {
/**
 * API base accepted by discovery, reused for subsequent model requests.
 */
base_url: string, models: Array<LlmModelOption>, };

export type ModelEnvironment = { kind: string, release: string, distro: string, ready: boolean, message: string, };

export type ModelRuntime = { engine_root: string, python_path: string, ready: boolean, message: string, };

export type CatalogModel = { id: string, purpose: string, name: string, languages: string, description: string, license: string, homepage: string, source_url: string, compatibility: string, note: string, };

export type InstalledModel = { id: string, purpose: string, model_id: string, name: string, path: string, ready: boolean, selected: boolean, message: string, };

export type ModelDownload = { id: string, model_id: string, state: string, message: string, downloaded_bytes: number, total_bytes: number, path: string, };

export type ModelLibrarySnapshot = { schema_version: number, environment: ModelEnvironment, runtime: ModelRuntime, scan_roots: Array<string>, installed: Array<InstalledModel>, catalog: Array<CatalogModel>, downloads: Array<ModelDownload>, selected_id: string | null, asr_selected_id: string | null, asr_error: string | null, };

export type LauncherServiceId = "server" | "tts" | "windows";

export type LauncherServiceState = "stopped" | "starting" | "running" | "stopping" | "failed" | "external";

export type LauncherService = { id: LauncherServiceId, state: LauncherServiceState, managed: boolean, message: string, url: string, log_path: string, can_start: boolean, can_stop: boolean, };

export type LauncherSetup = { configuration_path: string, server_config: string, llm_configured: boolean, llm_message: string, windows_client_path: string, };

export type LauncherSnapshot = { schema_version: number, session_token: string, services: Array<LauncherService>, setup: LauncherSetup, };

export type TrainingJob = { id: string, name: string, voice_id: string, status: string, progress: number, message: string, clip_count: number, created_at_ms: number, updated_at_ms: number, version_id: string | null, performance: TrainingPerformance, };

export type TrainingPerformance = { batch_size: number, data_workers: number, cpu_threads: number, gpu_index: number, low_memory: boolean, };

export type ModelVersion = { id: string, job_id: string, voice_id: string, name: string, engine: string, model_version: string, auditioned: boolean, saved: boolean, active: boolean, available: boolean, created_at_ms: number, };

export type TrainingSnapshot = { enabled: boolean, busy: boolean, jobs: Array<TrainingJob>, versions: Array<ModelVersion>, };

export type TrainingModelRuntimeSnapshot = { supported: boolean, state: string, message: string, };

export type TrainingModelRuntimeRequest = { enabled: boolean, };

export type TrainingClipMetadata = { text: string, language: string, };

export type TrainingTextMode = "audio_only" | "reviewed_text";

export type TrainingCreateRequest = { name: string, voice_id: string, sovits_epochs: number, gpt_epochs: number, reviewed: boolean, text_mode: TrainingTextMode, performance: TrainingPerformance, clips: Array<TrainingClipMetadata>, };

export type TrainingTranscribeRequest = { language: string, };

export type TrainingTranscription = { text: string, language: string, };

export type TrainingAuditionRequest = { version_id: string, text: string, };

export type RuntimeMeasurement = { measured_at_ms: number, llm_ms: number, tts_ms: number, total_ms: number, gpu_name: string, gpu_total_mib: number, gpu_peak_used_mib: number, voice_id: string, reply: string, passed: boolean, };

export type RuntimePresetSnapshot = { mode: string, model: string, local_only: boolean, verified: boolean, max_tokens: number, timeout_seconds: number, measurement: RuntimeMeasurement | null, message: string, };

export type RuntimeMeasureRequest = { voice_id: string, text: string, };

export type VoiceProfile = { id: string, name: string, language: string, reference_text: string, duration_ms: number, sample_rate: number, channels: number, available: boolean, error: string | null, };

export type CharacterMapping = { intent: string, hotkey_id: string, fallback_hotkey_id: string | null, validated: boolean, };

export type CharacterProfile = { id: string, name: string, model_id: string, voice_id: string, mouth_parameter: string, mappings: Array<CharacterMapping>, };

export type ResourceSnapshot = { voices: Array<VoiceProfile>, characters: Array<CharacterProfile>, active_voice_id: string, active_character_id: string | null, default_voice_available: boolean, };

export type VoiceCreateRequest = { name: string, language: string, reference_text: string, };

export type ResourceSelection = { id: string, };

export type CharacterSaveRequest = { id: string | null, name: string, model_id: string, voice_id: string, mouth_parameter: string, mappings: Array<CharacterMapping>, };

export type CharacterPreviewRequest = { character_id: string, intent: string, };

export type VtsModel = { id: string, name: string, };

export type ImportedModel = { id: string, name: string, model_id: string | null, };

export type VtsHotkey = { id: string, name: string, };

export type ObsOperation = { "type": "status" } | { "type": "set_scene", scene_name: string, } | { "type": "start_recording" } | { "type": "stop_recording" };

export type ObsSnapshot = { connected: boolean, recording: boolean, current_scene: string, scenes: Array<string>, };

export type ObsSettingsSnapshot = { enabled: boolean, websocket_url: string, password_configured: boolean, storage_available: boolean, };

export type ObsSettingsRequest = { enabled: boolean, websocket_url: string,
/**
 * None retains the current credential; clearing is always explicit.
 */
password: string | null, clear_password: boolean, };

export type DesktopResourceOperation = { "type": "obs_settings" } | { "type": "save_obs_settings", settings: ObsSettingsRequest, } | { "type": "obs", operation: ObsOperation, } | { "type": "list_models" } | { "type": "load_model", model_id: string, mouth_parameter: string, } | { "type": "list_hotkeys", model_id: string, } | { "type": "trigger_hotkey", model_id: string, hotkey_id: string, fallback_hotkey_id: string | null, } | { "type": "import_model" } | { "type": "list_imported_models" } | { "type": "delete_imported_model", id: string, };

export type DesktopResourceResult = { "type": "obs_settings", settings: ObsSettingsSnapshot, } | { "type": "obs", snapshot: ObsSnapshot, } | { "type": "models", models: Array<VtsModel>, } | { "type": "model_loaded", model_id: string, } | { "type": "hotkeys", model_id: string, hotkeys: Array<VtsHotkey>, } | { "type": "hotkey_triggered", hotkey_id: string, } | { "type": "model_imported", model_name: string, model_file: string, files: number, bytes: number, restart_required: boolean, } | { "type": "imported_models", models: Array<ImportedModel>, } | { "type": "model_deleted", id: string, restart_required: boolean, } | { "type": "error", code: string, message: string, };

export type LiveConnectionPhase = "disabled" | "disconnected" | "connecting" | "connected" | "reconnecting" | "disconnecting" | "failed";

export type LiveConnectionSnapshot = { platform: string, configured: boolean, phase: LiveConnectionPhase, room_id: string | null, accepted_events: number, duplicate_events: number, rejected_events: number, reconnect_attempts: number, last_error: string | null, };

export type LiveSettingsSnapshot = { enabled: boolean,
/**
 * A decimal string preserves application IDs larger than JavaScript's safe integers.
 */
app_id: string, access_key_id_configured: boolean, access_key_secret_configured: boolean, identity_code_configured: boolean, storage_available: boolean, };

export type LiveSettingsRequest = { enabled: boolean, app_id: string, access_key_id: string | null, access_key_secret: string | null, identity_code: string | null, clear_credentials: boolean, };

export type AgentSettings = { persona: string, system_prompt: string, topic: string, proactive_enabled: boolean, cooldown_ms: number, interaction: InteractionSettings, };

export type PersonaProfileSummary = { id: string, name: string, persona: string, };

export type PersonaProfilesSnapshot = { profiles: Array<PersonaProfileSummary>, selected_profile_id: string | null, storage_available: boolean, };

export type PersonaProfileCreateRequest = { name: string, persona: string, };

export type PersonaProfileIdRequest = { id: string, };

export type PersonaProfileRenameRequest = { id: string, name: string, };

export type PersonaProfileUpdateRequest = { id: string, name: string, persona: string, };

export type EventPayload = { "type": "chat", text: string, } | { "type": "gift", name: string, count: number, } | { "type": "super_chat", text: string, amount_cny: number, start_at_ms: number, end_at_ms: number, } | { "type": "room_enter" };

export type ViewerIdentityKind = "open_id" | "uid";

export type ViewerIdentityInput = { namespace: string, kind: ViewerIdentityKind, external_id: string, };

export type GiftMetadataInput = { price?: number, paid?: boolean, medal_level?: number, guard_level?: number, };

export type LiveEventInput = { id: string, source: string, viewer: string, viewer_identity?: ViewerIdentityInput, gift_metadata?: GiftMetadataInput, kind: EventPayload, };

export type EventBatchRequest = { events: Array<LiveEventInput>, };

export type EventBatchResult = { accepted: number, duplicates: number, persisted?: number, unscheduled?: number, };

export type AgentPhase = "paused" | "waiting" | "deciding" | "speaking";

export type AgentEventStatus = "pending" | "deciding" | "skipped" | "expired" | "queued" | "synthesizing" | "ready" | "playing" | "completed" | "cancelled" | "failed" | "unknown";

export type AgentEventSnapshot = { event: LiveEventInput, status: AgentEventStatus, speech_id: string | null, error: string | null, };

export type AgentSnapshot = { paused: boolean, phase: AgentPhase, settings: AgentSettings, events: Array<AgentEventSnapshot>, last_error: string | null, current_speech_id: string | null, llm_configured: boolean, bridge_connected: boolean, };

export type AudioFormat = { sample_rate: number, channels: number, };

export type AudioChunk = { utterance_id: string, generation: number, sequence: number, samples: Array<number>, end: boolean, };

export type SpeechRequest = { text: string, voice_id: string, };

export type SpeechStatus = "queued" | "synthesizing" | "ready" | "playing" | "completed" | "cancelled" | "failed" | "unknown";

export type SpeechSnapshot = { id: string, generation: number, text: string, voice_id: string, status: SpeechStatus, error: string | null, };

export type ServerStatus = { protocol_version: number, session_id: string, bridge_connected: boolean, generation: number, speeches: Array<SpeechSnapshot>, };

export type ServerHealth = { service: string, protocol_version: number, bridge_connected: boolean, };

export type ErrorResponse = { code: string, message: string, };

export type ExecutionStatus = "started" | "completed" | "cancelled" | "failed";

export type ExecutionReceipt = { utterance_id: string, generation: number, status: ExecutionStatus, error: string | null, };

export type ServerCommand = { "type": "hello", protocol_version: number, session_id: string, bridge_id: string, generation: number, } | { "type": "speak", utterance_id: string, generation: number, format: AudioFormat, } | { "type": "stop", generation: number, } | { "type": "resource", request_id: string, operation: DesktopResourceOperation, };

export type ClientMessage = { "type": "hello", protocol_version: number, } | { "type": "receipt", receipt: ExecutionReceipt, } | { "type": "resource_result", request_id: string, result: DesktopResourceResult, };

