// Generated by meowlive-protocol/export-types. Do not edit.

export const PROTOCOL_VERSION = 3 as const;

export type LlmSettings = { provider: string, api_format: string, base_url: string, model: string, mode: string, timeout_seconds: number, max_tokens: number, json_mode: boolean, };

export type LlmSettingsSnapshot = { settings: LlmSettings, key_configured: boolean, restart_required: boolean, active_model: string, storage_available: boolean, };

export type LlmSettingsRequest = { settings: LlmSettings, api_key: string | null, clear_api_key: boolean, };

export type LlmTestResult = { message: string, };

export type ModelEnvironment = { kind: string, release: string, distro: string, ready: boolean, message: string, };

export type ModelRuntime = { engine_root: string, python_path: string, ready: boolean, message: string, };

export type CatalogModel = { id: string, name: string, languages: string, description: string, license: string, homepage: string, source_url: string, compatibility: string, note: string, };

export type InstalledModel = { id: string, model_id: string, name: string, path: string, ready: boolean, selected: boolean, message: string, };

export type ModelDownload = { id: string, model_id: string, state: string, message: string, downloaded_bytes: number, total_bytes: number, path: string, };

export type ModelLibrarySnapshot = { schema_version: number, environment: ModelEnvironment, runtime: ModelRuntime, scan_roots: Array<string>, installed: Array<InstalledModel>, catalog: Array<CatalogModel>, downloads: Array<ModelDownload>, selected_id: string | null, };

export type LauncherServiceId = "server" | "tts" | "windows";

export type LauncherServiceState = "stopped" | "starting" | "running" | "stopping" | "failed" | "external";

export type LauncherService = { id: LauncherServiceId, state: LauncherServiceState, managed: boolean, message: string, url: string, log_path: string, can_start: boolean, can_stop: boolean, };

export type LauncherSetup = { configuration_path: string, server_config: string, llm_configured: boolean, llm_message: string, windows_client_path: string, };

export type LauncherSnapshot = { schema_version: number, session_token: string, services: Array<LauncherService>, setup: LauncherSetup, };

export type TrainingJob = { id: string, name: string, voice_id: string, status: string, progress: number, message: string, clip_count: number, created_at_ms: number, updated_at_ms: number, version_id: string | null, performance: TrainingPerformance, };

export type TrainingPerformance = { batch_size: number, data_workers: number, cpu_threads: number, gpu_index: number, low_memory: boolean, };

export type ModelVersion = { id: string, job_id: string, voice_id: string, name: string, engine: string, model_version: string, auditioned: boolean, saved: boolean, active: boolean, available: boolean, created_at_ms: number, };

export type TrainingSnapshot = { enabled: boolean, busy: boolean, jobs: Array<TrainingJob>, versions: Array<ModelVersion>, };

export type TrainingModelRuntimeSnapshot = { supported: boolean, state: string, message: string, };

export type TrainingModelRuntimeRequest = { enabled: boolean, };

export type TrainingClipMetadata = { text: string, language: string, };

export type TrainingTextMode = "audio_only" | "reviewed_text";

export type TrainingCreateRequest = { name: string, voice_id: string, sovits_epochs: number, gpt_epochs: number, reviewed: boolean, text_mode: TrainingTextMode, performance: TrainingPerformance, clips: Array<TrainingClipMetadata>, };

export type TrainingTranscribeRequest = { language: string, };

export type TrainingTranscription = { text: string, language: string, };

export type TrainingAuditionRequest = { version_id: string, text: string, };

export type RuntimeMeasurement = { measured_at_ms: number, llm_ms: number, tts_ms: number, total_ms: number, gpu_name: string, gpu_total_mib: number, gpu_peak_used_mib: number, voice_id: string, reply: string, passed: boolean, };

export type RuntimePresetSnapshot = { mode: string, model: string, local_only: boolean, verified: boolean, max_tokens: number, timeout_seconds: number, measurement: RuntimeMeasurement | null, message: string, };

export type RuntimeMeasureRequest = { voice_id: string, text: string, };

export type VoiceProfile = { id: string, name: string, language: string, reference_text: string, duration_ms: number, sample_rate: number, channels: number, available: boolean, error: string | null, };

export type CharacterMapping = { intent: string, hotkey_id: string, fallback_hotkey_id: string | null, validated: boolean, };

export type CharacterProfile = { id: string, name: string, model_id: string, voice_id: string, mouth_parameter: string, mappings: Array<CharacterMapping>, };

export type ResourceSnapshot = { voices: Array<VoiceProfile>, characters: Array<CharacterProfile>, active_voice_id: string, active_character_id: string | null, default_voice_available: boolean, };

export type VoiceCreateRequest = { name: string, language: string, reference_text: string, };

export type ResourceSelection = { id: string, };

export type CharacterSaveRequest = { id: string | null, name: string, model_id: string, voice_id: string, mouth_parameter: string, mappings: Array<CharacterMapping>, };

export type CharacterPreviewRequest = { character_id: string, intent: string, };

export type VtsModel = { id: string, name: string, };

export type ImportedModel = { id: string, name: string, model_id: string | null, };

export type VtsHotkey = { id: string, name: string, };

export type ObsOperation = { "type": "status" } | { "type": "set_scene", scene_name: string, } | { "type": "start_recording" } | { "type": "stop_recording" };

export type ObsSnapshot = { connected: boolean, recording: boolean, current_scene: string, scenes: Array<string>, };

export type DesktopResourceOperation = { "type": "obs", operation: ObsOperation, } | { "type": "list_models" } | { "type": "load_model", model_id: string, mouth_parameter: string, } | { "type": "list_hotkeys", model_id: string, } | { "type": "trigger_hotkey", model_id: string, hotkey_id: string, fallback_hotkey_id: string | null, } | { "type": "import_model" } | { "type": "list_imported_models" } | { "type": "delete_imported_model", id: string, };

export type DesktopResourceResult = { "type": "obs", snapshot: ObsSnapshot, } | { "type": "models", models: Array<VtsModel>, } | { "type": "model_loaded", model_id: string, } | { "type": "hotkeys", model_id: string, hotkeys: Array<VtsHotkey>, } | { "type": "hotkey_triggered", hotkey_id: string, } | { "type": "model_imported", model_name: string, model_file: string, files: number, bytes: number, restart_required: boolean, } | { "type": "imported_models", models: Array<ImportedModel>, } | { "type": "model_deleted", id: string, restart_required: boolean, } | { "type": "error", code: string, message: string, };

export type LiveConnectionPhase = "disabled" | "disconnected" | "connecting" | "connected" | "reconnecting" | "disconnecting" | "failed";

export type LiveConnectionSnapshot = { platform: string, configured: boolean, phase: LiveConnectionPhase, room_id: string | null, accepted_events: number, duplicate_events: number, rejected_events: number, reconnect_attempts: number, last_error: string | null, };

export type AgentSettings = { persona: string, topic: string, proactive_enabled: boolean, cooldown_ms: number, };

export type EventPayload = { "type": "chat", text: string, } | { "type": "gift", name: string, count: number, };

export type LiveEventInput = { id: string, source: string, viewer: string, kind: EventPayload, };

export type EventBatchRequest = { events: Array<LiveEventInput>, };

export type EventBatchResult = { accepted: number, duplicates: number, };

export type AgentPhase = "paused" | "waiting" | "deciding" | "speaking";

export type AgentEventStatus = "pending" | "deciding" | "skipped" | "expired" | "queued" | "synthesizing" | "ready" | "playing" | "completed" | "cancelled" | "failed" | "unknown";

export type AgentEventSnapshot = { event: LiveEventInput, status: AgentEventStatus, speech_id: string | null, error: string | null, };

export type AgentSnapshot = { paused: boolean, phase: AgentPhase, settings: AgentSettings, events: Array<AgentEventSnapshot>, last_error: string | null, current_speech_id: string | null, llm_configured: boolean, bridge_connected: boolean, };

export type AudioFormat = { sample_rate: number, channels: number, };

export type AudioChunk = { utterance_id: string, generation: number, sequence: number, samples: Array<number>, end: boolean, };

export type SpeechRequest = { text: string, voice_id: string, };

export type SpeechStatus = "queued" | "synthesizing" | "ready" | "playing" | "completed" | "cancelled" | "failed" | "unknown";

export type SpeechSnapshot = { id: string, generation: number, text: string, voice_id: string, status: SpeechStatus, error: string | null, };

export type ServerStatus = { protocol_version: number, session_id: string, bridge_connected: boolean, generation: number, speeches: Array<SpeechSnapshot>, };

export type ErrorResponse = { code: string, message: string, };

export type ExecutionStatus = "started" | "completed" | "cancelled" | "failed";

export type ExecutionReceipt = { utterance_id: string, generation: number, status: ExecutionStatus, error: string | null, };

export type ServerCommand = { "type": "hello", protocol_version: number, session_id: string, bridge_id: string, generation: number, } | { "type": "speak", utterance_id: string, generation: number, format: AudioFormat, } | { "type": "stop", generation: number, } | { "type": "resource", request_id: string, operation: DesktopResourceOperation, };

export type ClientMessage = { "type": "hello", protocol_version: number, } | { "type": "receipt", receipt: ExecutionReceipt, } | { "type": "resource_result", request_id: string, result: DesktopResourceResult, };

