\set ON_ERROR_STOP on
\getenv app_password MEOWLIVE_POSTGRES_APP_PASSWORD

BEGIN;
CREATE EXTENSION vector;
CREATE ROLE meowlive_app WITH LOGIN PASSWORD :'app_password'
    NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
REVOKE ALL ON DATABASE meowlive FROM PUBLIC;
GRANT CONNECT, TEMPORARY ON DATABASE meowlive TO meowlive_app;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO meowlive_app;
CREATE SCHEMA app AUTHORIZATION meowlive_app;
ALTER ROLE meowlive_app IN DATABASE meowlive SET search_path = app, public;
COMMIT;
